version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - communication-net
    restart: unless-stopped

  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter:latest
    ports:
      - "9419:9419"
    environment:
      - RABBITMQ_URL=http://guest:guest@rabbitmq:15672/
    networks:
      - communication-net
    depends_on:
      - rabbitmq
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - communication-net
    restart: unless-stopped

  redis-exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis:6379
    networks:
      - communication-net
    depends_on:
      - redis
    restart: unless-stopped

  consumer:
    image: consumer:latest
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__QueueName=message_queue
      - RabbitMQ__ExchangeName=messages-exchange
      - RabbitMQ__RoutingKey=messages.routing
      - RabbitMQ__IsEnabled=true
      - Redis__ConnectionString=redis:6379
      - Redis__IsEnabled=true
      - Kafka__IsEnabled=false
    networks:
      - communication-net
    depends_on:
      - rabbitmq
      - redis
    restart: unless-stopped

  server:
    image: server:latest
    ports:
      - "6061:6061"
      - "6062:6013"
      - "5277:5276"
    networks:
      - communication-net
    depends_on:
      - rabbitmq
      - redis
    restart: unless-stopped

  gateway:
    image: gateway:latest
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__QueueName=message_queue
      - RabbitMQ__ExchangeName=messages-exchange
      - RabbitMQ__RoutingKey=messages.routing
      - RabbitMQ__IsEnabled=true
      - Redis__ConnectionString=redis:6379
      - Redis__IsEnabled=true
      - Kafka__IsEnabled=false
    ports:
      - "6060:6060"
    networks:
      - communication-net
    depends_on:
      - rabbitmq
      - redis
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - communication-net
    depends_on:
      - gateway
      - consumer
      - redis-exporter
      - rabbitmq-exporter
    restart: unless-stopped

networks:
  communication-net:
    driver: overlay
