version: '3.8'

services:
  registry:
    image: registry:2
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: ingress
    networks:
      - communication-net
    volumes:
      - registry-data:/var/lib/registry
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - target: 5672
        published: 5672
        protocol: tcp
        mode: ingress
      - target: 15672
        published: 15672
        protocol: tcp
        mode: ingress
    environment:
      - RABBITMQ_DEFAULT_USER=exporter
      - RABBITMQ_DEFAULT_PASS=mypassword
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      communication-net:
        aliases:
          - rabbitmq
          - communication-tech_rabbitmq
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 20s
        max_attempts: 3
        window: 120s

  rabbitmq-exporter:
    image: kbudde/rabbitmq-exporter:latest
    ports:
      - target: 9419
        published: 9419
        protocol: tcp
        mode: ingress
    environment:
      - RABBIT_URL=http://rabbitmq:15672
      - RABBIT_USER=exporter
      - RABBIT_PASSWORD=mypassword
      - PUBLISH_PORT=9419
      - OUTPUT_FORMAT=TEXT
      - RABBIT_CAPABILITIES=bert,no_sort
    networks:
      communication-net:
        aliases:
          - rabbitmq-exporter
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 3
        window: 120s

  redis:
    image: redis:latest
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
        mode: ingress
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      communication-net:
        aliases:
          - redis
          - communication-tech_redis
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  redis-exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - target: 9121
        published: 9121
        protocol: tcp
        mode: ingress
    environment:
      - REDIS_ADDR=redis:6379
    networks:
      communication-net:
        aliases:
          - redis-exporter
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s

  consumer:
    image: localhost:5000/consumer:latest
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=exporter
      - RabbitMQ__Password=mypassword
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__QueueName=message_queue
      - RabbitMQ__ExchangeName=messages-exchange
      - RabbitMQ__RoutingKey=messages.routing
      - RabbitMQ__IsEnabled=true
      - Redis__ConnectionString=redis:6379,abortConnect=false,connectTimeout=30000,syncTimeout=30000
      - Redis__IsEnabled=true
      - Kafka__IsEnabled=false
    networks:
      - communication-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 5
        window: 120s

  server:
    image: localhost:5000/server:latest
    ports:
      - target: 6061
        published: 6061
        protocol: tcp
        mode: ingress
      - target: 6013
        published: 6062
        protocol: tcp
        mode: ingress
      - target: 5276
        published: 5277
        protocol: tcp
        mode: ingress
    networks:
      - communication-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  gateway:
    image: localhost:5000/gateway:latest
    environment:
      - Prometheus__Url=http://prometheus:9090
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Port=5672
      - RabbitMQ__UserName=exporter
      - RabbitMQ__Password=mypassword
      - RabbitMQ__VirtualHost=/
      - RabbitMQ__QueueName=message_queue
      - RabbitMQ__ExchangeName=messages-exchange
      - RabbitMQ__RoutingKey=messages.routing
      - RabbitMQ__IsEnabled=true
      - Redis__ConnectionString=redis:6379,abortConnect=false
      - Redis__IsEnabled=true
      - Kafka__IsEnabled=false
    ports:
      - target: 6060
        published: 6060
        protocol: tcp
        mode: ingress
    volumes:
      # Host path -> Container path
      - /home/ubuntu/Communication.Tech/results:/app/results
    networks:
      - communication-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 120s

  prometheus:
    image: prom/prometheus:latest
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: ingress
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    networks:
      - communication-net
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    deploy:
      mode: global
    ports:
      - "9100:9100"
    networks:
      - communication-net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude="^/(sys|proc|dev|etc)($|/)"'

networks:
  communication-net:
    driver: overlay
    attachable: true
    
volumes:
  registry-data:
    driver: local

configs:
  prometheus_config:
    file: ./prometheus.yml