version: '3.8'

services:
  communication.tech.gateway:
    build:
      context: .
      dockerfile: Communication.Tech.Gateway/Dockerfile
    ports:
      - "5059:5059"  # metrics ve routing port
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTPS_PORT=
      - DOTNET_RUNNING_IN_CONTAINER=true
      - Kafka__BootstrapServers=kafka:9092
      - RabbitMQ__HostName=rabbitmq
      - Redis__ConnectionString=redis:6379
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - tech-net
        
  communication.tech.server:
    build:
      context: .
      dockerfile: Communication.Tech.Server/Dockerfile
    ports:
      - "5060:5060"  # HTTP
      - "6011:6011"  # gRPC
      - "5273:5273"  # WebSocket
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTPS_PORT=
      - Kestrel__Endpoints__Http__Url=http://+:5060
      - Kestrel__Endpoints__Grpc__Url=http://+:6011
      - Kestrel__Endpoints__WebSocket__Url=http://+:5273
      - Kafka__BootstrapServers=kafka:9092
      - RabbitMQ__HostName=rabbitmq
      - Redis__ConnectionString=redis:6379
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - tech-net
  communication.tech.consumer:
    build:
      context: .
      dockerfile: Communication.Tech.Consumer/Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Kafka__BootstrapServers=kafka:9092
      - RabbitMQ__HostName=rabbitmq
      - Redis__ConnectionString=redis:6379
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - tech-net

  # Prometheus monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - communication.tech.gateway
      - communication.tech.consumer
    networks:
      - tech-net

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - tech-net

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # Web UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - tech-net

  # Zookeeper (Kafka)
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - tech-net

  # Kafka
  kafka:
    image: bitnami/kafka:latest
    container_name: communicationtech-kafka-1
    environment:
      # KRaft Mode Configuration
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      
      # Listener Configuration
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      
      # Other settings
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_CFG_LOG_RETENTION_HOURS: 168
      
    ports:
      - "9092:9092"
    networks:
      - tech-net
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  tech-net:
    driver: bridge
