version: '3.8'

services:
  communication.tech.gateway:
    build:
      context: .
      dockerfile: Communication.Tech.Gateway/Dockerfile
    ports:
      - "5059:5059"  # metrics ve routing port
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=true
      - Kafka__BootstrapServers=kafka:9092
      - RabbitMQ__HostName=rabbitmq
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis
      - kafka
      - rabbitmq
    networks:
      - tech-net
        
  communication.tech.server:
    build:
      context: .
      dockerfile: Communication.Tech.Server/Dockerfile
    ports:
      - "5060:5060"  # HTTP
      - "6011:6011"  # gRPC
      - "5273:5273"  # WebSocket
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTPS_PORT=
      - Kestrel__Endpoints__Http__Url=http://+:5060
      - Kestrel__Endpoints__Grpc__Url=http://+:6011
      - Kestrel__Endpoints__WebSocket__Url=http://+:5273
      - Kafka__BootstrapServers=kafka:9092
      - RabbitMQ__HostName=rabbitmq
      - Redis__ConnectionString=redis:6379
    depends_on:
      - kafka
      - redis
      - rabbitmq
    networks:
      - tech-net

  communication.tech.consumer:
    build:
      context: .
      dockerfile: Communication.Tech.Consumer/Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Kafka__BootstrapServers=kafka:9092
      - RabbitMQ__HostName=rabbitmq
      - Redis__ConnectionString=redis:6379
    depends_on:
      - communication.tech.server
      - redis
      - kafka
      - rabbitmq
    networks:
      - tech-net

  # Prometheus monitoring
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - communication.tech.gateway
      - communication.tech.consumer
    networks:
      - tech-net

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - tech-net

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # Web UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - tech-net

  # Zookeeper (Kafka)
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - tech-net

  # Kafka
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - tech-net

networks:
  tech-net:
    driver: bridge