global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'consumer'
    static_configs:
      - targets: ['consumer:8080']
    metrics_path: '/metrics'
    
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'server'
    static_configs:
      - targets: ['server:6061']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:6060']
        
  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node_exporter:9100' ]

  - job_name: 'kafka_exporter'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]
